// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PizzaServer
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for DeletePizzaUsingDELETE.
    /// </summary>
    public static partial class DeletePizzaUsingDELETEExtensions
    {
            /// <summary>
            /// Deletes a topping
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The topping ID
            /// </param>
            public static void One(this IDeletePizzaUsingDELETE operations, long id)
            {
                Task.Factory.StartNew(s => ((IDeletePizzaUsingDELETE)s).OneAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes a topping
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The topping ID
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task OneAsync(this IDeletePizzaUsingDELETE operations, long id, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.OneWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
